# Generated by Django 2.2.16 on 2022-11-07 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(
                help_text='Укажите автора данного поста',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='posts',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Автор'
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(
                blank=True,
                help_text='Вставьте изображение',
                upload_to='posts/',
                verbose_name='Картинка'
            ),
        ),
    ]
